services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Padam87\BillingoBundle\Service\Authenticator:
        arguments:
            $config: '%padam87_billingo.config%'

    Padam87\BillingoBundle\Service\Api:
        arguments:
            $config: '%padam87_billingo.config%'

    Padam87\BillingoBundle\Service\Helper: ~
    Padam87\BillingoBundle\Form\Type\PaymentMethodType: ~
    Padam87\BillingoBundle\Form\Type\BankAccountType: ~

    padam87_billingo.api:
        alias: 'Padam87\BillingoBundle\Service\Api'
        public: true

    padam87_billingo.helper:
        alias: 'Padam87\BillingoBundle\Service\Helper'
        public: true
