services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Padam87\BillingoBundle\Service\Authenticator: ~
    Padam87\BillingoBundle\Service\Api: ~
    Padam87\BillingoBundle\Service\Helper: ~
    Padam87\BillingoBundle\Form\Type\PaymentMethodType: ~

    padam87_billingo.api:
        alias: 'Padam87\BillingoBundle\Service\Api'
        public: true

    padam87_billingo.helper:
        alias: 'Padam87\BillingoBundle\Service\Helper'
        public: true
